# Generated by Django 5.0.6 on 2024-08-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocios',
            name='path_imagen',
        ),
        migrations.AddField(
            model_name='negocios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='statics/imagen/negocios/'),
        ),
    ]
