# Generated by Django 5.0.6 on 2024-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0005_alter_negocios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocios',
            name='imagen',
            field=models.ImageField(default='Supermarket/static/imagen/negocios/base_supermarket.jpg', upload_to='Supermarket/static/imagen/negocios/'),
        ),
    ]
