# Generated by Django 5.0.6 on 2024-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0007_alter_negocios_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='path_imagen',
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='static/imagen/productos/base_productos.jpg', upload_to='static/imagen/productos/'),
        ),
    ]
