# Generated by Django 5.0.6 on 2024-08-09 21:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0008_remove_productos_path_imagen_productos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
        migrations.AddField(
            model_name='productos',
            name='id_categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='Supermarket.categorias'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Precio_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 18, 9, 57, 830728))),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='Supermarket.productos')),
            ],
        ),
    ]
