# Generated by Django 5.0.6 on 2024-08-09 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0009_remove_productos_precio_productos_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio_producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 18, 10, 35, 651218)),
        ),
    ]
