# Generated by Django 5.0.6 on 2024-08-09 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0012_alter_precio_producto_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.AlterField(
            model_name='precio_producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 19, 35, 33, 900409)),
        ),
    ]
