# Generated by Django 5.0.6 on 2024-08-09 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0014_alter_precio_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio_producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 19, 36, 3, 527229)),
        ),
    ]
